### ISSUE TITLE
Plan, roadmap the Python 2 to 3 migration

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#5898]
Acceptance Criteria:

- [ ] document a plan stating the next steps after Python 3 code updates are complete
- [ ] once the documented plan is completed create any needed issues/work to move this forward
- [ ] once the documented plan is complete it needs to be shared with the Dev team and Content team so that they are aware of upcoming demands on them (e.g. the need for a week of no-deploys, or content team testing on staging)

**Comment by atopal** [comment]
This was done yesterday
