### ISSUE TITLE
Display step progress on Create MDN Profile page

### ISSUE THREAD

**Issue by nickbrandt** [mdn/kuma#6041]
# User story
As a user, I want to understand where I am at in the process of creating an MDN account, so that I know that I am almost complete with the process.

# Acceptance criteria

- [x] First step displays authorized by Github
- [x] Displays the auth service's logo in first step
- [x] Second step (current step on page) is "Create MDN Profile"
- [x] Displays user avatar pulled from Github in the second step (if available), otherwise display MDN's default avatar (dino head)
- [x] Shows indicator that the first step is complete (checkmark)
- [x] user stays on developer.mozilla.org not wiki.developer.mozilla.org

# Tasks

See https://github.com/mozilla/kuma/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+project%3Amozilla%2Fkuma%2F1

# Design

Github Auth:
InVision: https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/368129372_Create_Account_-_MDN_Profile
Zeplin: https://zpl.io/2jYxqKp

Google Auth:
InVision: https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/370705985_Create_Account_-_MDN_Profile_-google-
Zeplin: https://zpl.io/VOA8L3r

Avatar Available:
InVision: https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/374095626_Create_Account_-_MDN_Profile_-alt_-_With_Pic-
Zeplin: https://zpl.io/aX9NRqp

Mobile version (without header/footer): https://zpl.io/2v0ejgQ

**Comment by tobinmori** [comment]
@jmswisher should we convert this to an epic?

**Comment by schalkneethling** [comment]
This one is complete. Closing.
