### ISSUE TITLE
T - Create feature matrix, and decide which features not to support (now)

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6122]
Acceptance Criteria:

- [x] A document that shows front-end features of MDN and compares these features against Stumptown renderer the goal of which is to determine which features to support in Yari 2
- [x] List missing features (now)
- [ ] List upcoming features that will need parity (now)
- [ ] List what missing features are straight forward, and which ones are fraught with risk (now)

**Comment by tobinmori** [comment]
https://docs.google.com/document/d/1uUxPGdLJsiUVguQu1Hy_taMsVlQJ0DnbUoL8Ky1pE4o/

**Comment by tobinmori** [comment]
@peterbe to convert to spreadsheet.

**Comment by jmswisher** [comment]
@tobinmori @peterbe This issue is not in the spreadsheet for Ursula Rucker. Is it in the sprint (add to spreadsheet) or out (remove milestone)?

**Comment by tobinmori** [comment]
Thanks @jmswisher - I removed the milestone, as @peterbe has a full plate this sprint.
