### ISSUE TITLE
E - Update foundational dependencies (especially Django)

### ISSUE THREAD

**Issue by callahad** [mdn/kuma#6167]
Now that we've moved to Python 3 (#5943), it's time to turn our attention to the libraries that Kuma relies on.

__Django 1.11 reaches [end-of-life in April 2020](https://www.djangoproject.com/download/#supported-versions).__ To ensure the security and maintainability of Kuma, we must upgrade ot Django 2 before that date. Django 2 is supported until April 2022.

Additionally, at least 70 more of our approximately 120 dependencies are outdated, which should be updated as well.

Tasks:

- [ ] Upgrade to Django 2.x (#6172)
- [x] Upgrade other libraries where possible (#6173)
- [x] Use modern tools for dependency management (e.g., [Poetry](https://poetry.eustace.io/) or [Pipenv](https://pipenv.kennethreitz.org/)) (#6174)
- [ ] Configure Dependabot to automatically send pull requests for future dependency updates (#6175)

**Comment by tobinmori** [comment]
@tobinmori convert to epic/subtickets.
