### ISSUE TITLE
T - Upgrade to Django 2.2

### ISSUE THREAD

**Issue by callahad** [mdn/kuma#6172]
Django 1.11 reaches [end-of-life in April 2020](https://www.djangoproject.com/download/#supported-versions).

To ensure the security and maintainability of Kuma, we must upgrade ot Django 2 before that date. Django 2 is supported until April 2022.

Part of Epic #6167 

## Blockers / Necessary Tasks

- [x] [(comment)](https://github.com/mdn/kuma/issues/6172#issuecomment-586203805) Assess current dependencies for Django 2 support
- [x] https://github.com/ubernostrum/django-soapbox/pull/6 Address django-soapbox incompatibility with Django 2
- [x] #6516 - Rewrite our i18n_patterns function to not rely on Django's LocaleRegexURLResolver
- [x] #6537 - Remove custom StrippedCharField
- [x] #6564 - Address collision with custom view_document permission
- [x] #6565 - Test failures: Django 2's truncatechars uses a real elipsis
- [x] #6566 - Test failures: Cannot encode None as POST data
- [x] #6567 - Test failures: User.has_usable_password() unexpectedly True
- [x] #6568 - Test failures: Sitemap has excess entries
- [x] #6569 - Test failures: Mail handler has excess item in outbox
- [x] #6596 - localeextract fails in Django 2
- [x] [(comment)](https://github.com/mdn/kuma/issues/6172#issuecomment-586268788) Manually verify at-risk dependencies identified in assessment

**Comment by callahad** [comment]
Right now our Python code has 80 direct dependencies and 47 indirect dependencies. I'm reviewing these to determine if:

1. We actually use our declared dependencies
2. We do not accidentally rely on an indirect dependency
3. Which dependencies are might be affected by a Django upgrade

Once I do that, I'll look through the list of affected modules, determine if they support Django 2, and figure out a plan to move forward with each of them.

When our dependencies are ready to go, I'll start reviewing the core Django 2 upgrade docs and working toward implementing the upgrade.

**Comment by callahad** [comment]
Dependency audit completed in #6498

Dependencies that may be affected by upgrading Django:

| Dependency Name | OK? | Notes |
| - |:-:| - |
| dj-database-url | ❓ | |
| dj-email-url | ❓ | |
| django | ❓ | |
| django-allauth | ❓ | |
| django-babel | ❓ | |
| django-cacheback | ❓ | |
| django-constance | ❓ | |
| django-csp | ❓ | |
| django-debug-toolbar | ❓ | |
| django-decorator-include | ❓ | |
| django-extensions | ❓ | |
| django-honeypot | ❓ | |
| django-jinja | ❓ | |
| django-mysql | ❓ | |
| django-pipeline | ❓ | |
| django-querycount | ❓ | |
| django-ratelimit | ❓ | |
| django-redirect-urls | ❓ | |
| django-redis | ❓ | |
| django-soapbox | ❓ | |
| django-statici18n | ❓ | |
| django-storages | ❓ | |
| django-sundial | ❓ | |
| django-taggit | ❓ | |
| django-tidings | ❓ | |
| django-waffle | ❓ | |
| djangorestframework | ❓ | |
| mysqlclient | ❓ | |
| puente | ❓ | |
| pytest-django | ❓ | |
| raven | ❓ | |
| whitenoise | ❓ | |

**Comment by callahad** [comment]
So, where are we?

We need to fix or replace the following libraries before updrading Django:

- __django-soapbox__
  Throws at least one `RemovedInDjango20Warning`
  Trivial to patch, but other issues may be lurking

We need to upgrade the following at the same time that we upgrade Django:

- __django-decorator-include__ → 2.1
- __django-taggit__ → 0.24.0

We need to manually validate the functioning of:

- __django-ratelimit__
  See [reported issue](https://github.com/jsocol/django-ratelimit/issues/186) and workaround

- __django-babel__
  Switch to [enmerkar](https://github.com/Zegocover/enmerkar) if fails

- __django-querycount__
  Dev dependency; remove if fails
  (Potentially redundant with the Django Debug Toolbar?)

- __django-redirect-urls__
  Expected to work; talk to pmac if it doesn't

- __django-cacheback__
  Expected to work

- __puente__
  Expected to work

**Comment by peterbe** [comment]
Some notes...

- __django-soapbox__
  I fear we still need it, but perhaps it would be easy to just create another django *app* here inside our `kuma` package. Literally copy it from the `lib/python/site-packages/soapbox` into `~/projects/kuma/kuma/` and just bang smash it till it works. It might require some hacks. I still think it's a useful feature to have but with Yari it's going to go away completely. 

- __django-decorator-include__ → 2.1
  That was my conclusion too when I looked at it in conjunction with py3. 

- __django-querycount__
   I added that one. But now I rarely use it. It's better than debug-toolbar because it can give you insights on ORM/SQL usage, per request on Django views that don't return a rendered jinja template. Kill it if you have to.

**Comment by callahad** [comment]
Upstream pull request for django-soapbox at https://github.com/ubernostrum/django-soapbox/pull/6

If James doesn't merge it over the weekend I'll either publish my fork (`django-soapbox-hospice`?) or vendor the fixed code into Kuma.

**Comment by callahad** [comment]
My patches were merged and django-soapbox 1.6 is now available on PyPI with support for Django 2. Requires simultaneous upgrade of Django.
