### ISSUE TITLE
Payments: add MDN-styled Stripe payment modal

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6184]
**Description:** 
Stripe modal with MDN-styling. This work will also including JS that submits charge to Stripe.

**Invision Design:**
https://mozilla.invisionapp.com/share/8AUY90P273Y#/screens/394804915

**Stripe docs:**
https://stripe.com/docs/payments/checkout/subscriptions/starting
https://stripe.com/docs/payments/checkout/customization

**Acceptance criteria:**
- [ ] MDN-styled Stripe modal appears when 'Continue' is clicked from User Acct Edit page (see #6183) and modal accepts Email/CC/remember me
- [ ] User clicks Pay button and payment is submitted to Stripe via JS call
- [ ] Stripe cust id is stored in user.stripe_customer_id
- [ ] User is redirected to back to User Acct page with Confirmation at bottom (see #6185)
- [ ] the modal is only shown to staff users via a feature flag

**Notes:**
Please talk to Tobin about Stripe integration/access

**Previous version:**
https://github.com/mdn/kuma/pull/5423

**Comment by Gregoor** [comment]
@atopal @malqinneh I just learned that [Stripe deprecated the payment modal](https://stripe.com/docs/payments/checkout/migration). It's been replaced by [Checkout](https://stripe.com/docs/payments/checkout) which takes user to a site hosted by stripe. If we want a little more customizability and keep people on our site we can use [Elements](https://stripe.com/en-de/payments/elements). And if that is not enough we can go fully custom (while ofc still using stripe for handling the subscription).
I err towards the former because it's the easiest option which seems appropriate for this intial version.

**Comment by malqinneh** [comment]
@Gregoor I thought they did but @atopal confirmed that they were still using the modal workflow for payments. We do have a version of the workflow using Stripe's new dedicated page. I can share that with you if it helps but I'd check with @tobinmori and @atopal first :)

**Comment by Gregoor** [comment]
Right, that seems to be one of the drivers (as well as ApplePay which I assume we don't care too much about either 😁). Just wanted to point out that this might get an expiration date.
