### ISSUE TITLE
E - User flow instrumented

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6283]
# User story
As the PM I want our new user flow to be instrumented so we can identify bottle necks

# Context
We have a new user flow that will hopefully allow more users to easily get an MDN account. We have already talked about some potential confusing screens. Instrumenting the flow should allow us to identify issues and check whether our optimizations are working. 

## My questions:
1. How many people have tried to sign up to MDN on any given day (not sign in to an account)?
2. How many people have tried to sign in to MDN on any given day?
3. How many users chose Google to sign up? 
4. How many users chose Github to sign up? 
5. How many users signed in with Google? 
6. How many users signed in with Github? 
7. How many Google users came back to create their profile?
8. How many Github users came back to create their profile?
9. How many people clicked to edit their username?
10. How many people clicked to change their email address?
11. How many people saw a username error?
12. How many people saw an email error?
13. How many people opted in to receive news?
14. How many people opted out of receiving news?
15. How many people ended up creating an account?
16. How many people ended up creating an account authenticated with Google?
17. How many people ended up creating an account authenticated with Github?

## Breakdown for events
category | action | label
3. ~~signup-flow | sign-up | Google~~ --> `signup-flow | auth-started | Google` (Google button in multi-auth modal pushed)
4. ~~signup-flow | sign-up | Github~~ --> `signup-flow | auth-started | GitHub` (GitHub button in multi-auth modal pushed)
5. ~~signup-flow | sign-in | Google~~ --> `signup-flow | returning-user-signin | Google`
6. ~~signup-flow | sign-in | Github~~ --> `signup-flow | returning-user-signin | GitHub`
7. `signup-flow | profile-audit | Google`
8. `signup-flow | profile-audit | Github`
9. `signup-flow | profile-edit | username edit`
10. `signup-flow | profile-edit | email edit`
11. `signup-flow | profile-edit-error | username`
12. `signup-flow | profile-edit-error | email`
13. `signup-flow | free-newsletter | opt-in`
14. `signup-flow | free-newsletter | opt-out`
16. `signup-flow | profile-created | Google`
17. `signup-flow | profile-created | Github`

# Acceptance criteria
- [x] sign-up events are implemented
- [x] sign-in events are implemented
- [x] profile events are implemented
- [x] newsletter events are implemented
- [x] test run successfully documented
- [x] Google analytics dashboard created for analysis

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [x] This is an incomplete task.

**Comment by peterbe** [comment]
These are all server-side events and aggregates. 
If we're going to use Google Analytics as the reporting UI, we should implement [Measurement Protocol](https://developers.google.com/analytics/devguides/collection/protocol/v1) and there are what appears to be some decent Python libraries for that. E.g. https://github.com/mirumee/google-measurement-protocol

I think aggregates belongs in the reporting so in a sense, the aggregate reporting could belong to an epic and *this* issue can be about adding the event instrumentation into the Django pipes.

**Comment by atopal** [comment]
@peterbe just seeing this comment now. Can you tell what you mean by aggregates? I don't expect anything other than atomic events, GA is the platform that would answer the question "how many?"

**Comment by peterbe** [comment]
I phrased myself poorly I see now. These are all individual events that all lead up to being able to do aggregates. Like, of course they are. I'll make sure we're *sending* these individual events and then we can join forces to look into GA to make sure we can answer all the questions.

**Comment by atopal** [comment]
At this point I care most about events 3-6 and 13-17.

**Comment by tobinmori** [comment]
subtasks added:
#6413, #6414

**Comment by chinikes** [comment]
Hi @peterbe , @tobinmori  - Wanted to confirm that the 3 attached tasks- #6413, #6414 and #6462 represent the steps needed to complete this Story?

**Comment by peterbe** [comment]
> Hi @peterbe , @tobinmori - Wanted to confirm that the 3 attached tasks- #6413, #6414 and #6462 represent the steps needed to meet the acceptance criteria of this Story?

I believe so.

**Comment by tobinmori** [comment]
> Hi @peterbe , @tobinmori - Wanted to confirm that the 3 attached tasks- #6413, #6414 and #6462 represent the steps needed to meet the acceptance criteria of this Story?

Yes @chinikes that's correct.

**Comment by peterbe** [comment]
I believe we are code complete on this one!!
Now it just needs to be tested.

**Comment by tobinmori** [comment]
A GA report as been setup called "Signup Flow Report" (under Saved Reports).
