### ISSUE TITLE
E - Define GitHub File Organization for Yari

### ISSUE THREAD

**Issue by escattone** [mdn/kuma#6443]
#### Summary
The outcome of this epic is that we have defined a GitHub file organization for our content, both in terms of folder hierarchy, file formats and content, and filename conventions.

#### Breakdown of sub-tasks | Acceptance Criteria 
- [x] Document a comprehensive list of questions/issues that the file organization must be able to answer/resolve (e.g., does it provide a relatively-friendly contributor experience?, what are a document's parents?, etc.) (#6441)
- [x] Study the file organization of several other documentation projects that are using GitHub for storing their content (https://github.com/mdn/kuma/issues/6124)
- [x] Develop one or more solutions, with the aid of the results of our study of other projects, that satisfy our criteria. (#6444)
- [x] Document our decisions. (#6442)

**Comment by chinikes** [comment]
@atopal , @tobinmori , @escattone - Can we confirm the output from the "Breakdown of Sub-Tasks" listed in the description as the acceptance criteria for this epic?

**Comment by escattone** [comment]
> @atopal , @tobinmori , @escattone - Can we confirm the output from the "Breakdown of Sub-Tasks" listed in the description as the acceptance criteria for this epic?

@chinikes Yes, speaking for myself, I would say that is the case.

**Comment by atopal** [comment]
That works for me too.
