### ISSUE TITLE
E - Implement new design for mobile article pages

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#6506]
# Epic | Milestone 
As an MDN user on a mobile device, I want a clean header so I can get to the content I'm really interested in 

# Acceptance criteria
- [x] Breadcrumbs on mobile are optimized for mobile 
- [x] The MDN header is optimized for mobile 
- [x] The Table of Contents are optimized for mobile 
- [x] The Sidebar is optimized for mobile 
- [x] The footer is optimized for mobile 

# User Stories
1. - U - Optimize Breadcrumbs, header and footer for mobile 
2. - U - Optimize Table of Contents for mobile 
3. - U - Create design for Optimized Sidebar for mobile

**Comment by chinikes** [comment]
Hi @malqinneh, @atopal - Can you help identify user stories that satisfy the acceptance criteria for this epic? We need this fleshed out as ZenHub cards before planning next week.
