### ISSUE TITLE
U - As the MDN PM I want a banner on every MDN page with a CTA for monthly payment, so we can let people know about that option

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6554]
# User story
As the MDN PM I want a banner on every MDN page with a CTA for monthly payment, so we can let people know about that option

# Acceptance criteria
- [x] Banner is shown on every page (or at least document pages and start page)
- [x] Banner is only shown on desktop
- [x] Banner is not shown on profile
- [x] Banner shows up immediately on page load
- [x] Banner is sticky to the bottom of the view port
- [x] Banner has a link to FAQ
- [x] Banner has option to be dismissed
- [x] Dismissing the banner won't show it again for 7 days, and is shown again after 7 days
- [x] Banner is not shown for paying subscribers.

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

# Context
To launch incrementally, we'll implement the banner, but on clicking subscribe, the potential subscriber is taken to their profile, where they can make a payment. In subsequent user stories we'll expand that to to open a modal to pay in place. 

# Design

- Signed in user:
 https://share.goabstract.com/857f8a74-8fdd-41e6-9d78-d5c838d4054a?mode=design
- Non-signed in users (but with an account): 
 https://share.goabstract.com/857f8a74-8fdd-41e6-9d78-d5c838d4054a?collectionLayerId=1c005660-47c6-4d98-aac5-bc533fa9ae26&mode=design
- Non-signed in users (without an account): 
https://share.goabstract.com/857f8a74-8fdd-41e6-9d78-d5c838d4054a?collectionLayerId=0083a875-bdc1-49e2-9215-9a0c59a4cab6&mode=design
- And then the specific use-case where you have the banner take you to the user profile/settings page(?): https://share.goabstract.com/80aff1b8-a8da-4250-ab33-f6426d45b2e1?mode=design

**Comment by tobinmori** [comment]
task #6577

**Comment by peterbe** [comment]
What more needs to be done to close this? The only task for this user story is resolved.

**Comment by tobinmori** [comment]
Nothing, but @atopal is the official closer of User Stories. 

@atopal this should be viewable on prod now.

**Comment by chinikes** [comment]
@schalkneethling - Wanted to confirm if there's a task to be created to satisfy the last bit of the AC - "**_Banner is not shown for paying subscribers_**." ? 
cc: @atopal , @tobinmori

**Comment by schalkneethling** [comment]
> @schalkneethling - Wanted to confirm if there's a task to be created to satisfy the last bit of the AC - "**_Banner is not shown for paying subscribers_**." ?
> cc: @atopal , @tobinmori

@peterbe did land a solution for that but, I am not 100% that it is in production. There was a push yesterday though so, I am rather confident it will be in production now.

**Comment by atopal** [comment]
@peterbe can you verify this is fixed? I don't think I can test this?

**Comment by peterbe** [comment]
> @peterbe can you verify this is fixed? I don't think I can test this?

1. First I delete the localStorage
<img width="1455" alt="Screen Shot 2020-04-02 at 7 17 50 AM" src="https://user-images.githubusercontent.com/26739/78243645-20b5af80-74b2-11ea-83b0-f7fd4450893b.png">

2. Then I go to the Edit Profile and from there click to the subscription management page and cancel my subscription.
<img width="1476" alt="Screen Shot 2020-04-02 at 7 19 18 AM" src="https://user-images.githubusercontent.com/26739/78243750-4c389a00-74b2-11ea-92f8-f6f087b5b782.png">

3. Go back to the read-only site (because the subscription management page jumps you over to the wiki) so back to http://localhost.org:8000/en-US/
<img width="1440" alt="Screen Shot 2020-04-02 at 7 20 51 AM" src="https://user-images.githubusercontent.com/26739/78243844-80ac5600-74b2-11ea-9506-04e08e0805c3.png">

So yes, it's working in `master`. The banner basically depends on 3 things

1. waffle flag
2. `localStorage`
3. `/api/v1/whoami`

All seems right and well.

**Comment by atopal** [comment]
Thanks Peter!

**Comment by chinikes** [comment]
@atopal , @peterbe - With all ACs marked as done, can we mark this user story as Closed at this point?

**Comment by peterbe** [comment]
I can't think of any task that needs to be addressed, but I think @atopal closes user story issues.

**Comment by atopal** [comment]
yeah, we demoed this yesterday, all good.
