### ISSUE TITLE
U - As the MDN PM I want a payment option on the FAQ page, so we can link to it.

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6556]
# Acceptance Criteria
- [x] FAQ page has payment option at the top of the page that matches design
- [x] signed in users who accept the payment terms see the stripe modal.
- [x] signed in users who complete the stripe modal are forwarded to the thank you page.
- [x] upon cancelling the stripe modal, users are back on the FAQ page.
- [x] People who are already subscribed see a "thank you" message and no subscribe form

# Context
The FAQ page is the landing page for subscriptions. It's the place we can link to from other places off of MDN (eg. newsletter). That means we need the capability to make payments on that page.

# Design

- Signed in user:
 https://share.goabstract.com/857f8a74-8fdd-41e6-9d78-d5c838d4054a?mode=design
- Non-signed in users (but with an account): 
 https://share.goabstract.com/857f8a74-8fdd-41e6-9d78-d5c838d4054a?collectionLayerId=1c005660-47c6-4d98-aac5-bc533fa9ae26&mode=design
- Non-signed in users (without an account): 
https://share.goabstract.com/857f8a74-8fdd-41e6-9d78-d5c838d4054a?collectionLayerId=0083a875-bdc1-49e2-9215-9a0c59a4cab6&mode=design
- And then the specific use-case where you have the banner take you to the user profile/settings page(?): https://share.goabstract.com/80aff1b8-a8da-4250-ab33-f6426d45b2e1?mode=design

**Comment by chinikes** [comment]
@schalkneethling , @atopal , @tobinmori - This story has been marked done on the spreadsheet. Can you confirm the ACs have been met? Thanks!

**Comment by Gregoor** [comment]
@peterbe just made me aware that none of the tasks yet describe how the `/payments` page changes once a user subscribes. I get that immediately after subscribing they're redirect to `/payments/thank-you`. Though that one also links back to payments as tit has the FAQ as well. Is the idea to just hide the header? I also don't seem to find an answer to that in the Designs.

cc @malqinneh

**Comment by malqinneh** [comment]
@Gregoor Ah you're right, we did not show how this scenario could be handled. I think we can handle it by using the same header as `/payments/thank-you` see below:

![Sub_Thank-You - 02 - Incentive@1x](https://user-images.githubusercontent.com/4819906/77661097-8f45bb00-6f50-11ea-83d6-dbcf6955d181.jpg)

**Comment by Gregoor** [comment]
Makes sense and works for me. Thanks Mustafa!

**Comment by peterbe** [comment]
@malqinneh No link to manage your subscription there? I know it's deep down in the FAQ, but perhaps that whole sentence "You are MDN member number 1,234" could be a link to the subscription management page. 

Also, sorry for nitpicking but isn't it "You are MDN SUBSCRIBBER number 123" because anybody who signs in becomes a member. No?

**Comment by malqinneh** [comment]
@peterbe if we notice subscribers visiting the payments page to manage their subscription and are confused about how to manage their subscription, we can resolve the issue then.

Re: copy; anybody that signs up for an account becomes a user, subscribers become members. We don't announce 'membership' for normal account sign ups.

**Comment by peterbe** [comment]
> if we notice subscribers visiting the payments page to manage their subscription and are confused about how to manage their subscription, we can resolve the issue then.

I think it would be really easy to add a link to this page from the signed-in drop-down (when you click your mugshot). It's so weird that, after you've become a subscriber, I have to click into the Edit Profile and scroll to the bottom.

**Comment by atopal** [comment]
Looks good to me, @malqinneh

**Comment by malqinneh** [comment]
> I think it would be really easy to add a link to this page from the signed-in drop-down (when you click your mugshot). It's so weird that, after you've become a subscriber, I have to click into the Edit Profile and scroll to the bottom.

I agree that it's easy adding a link in the header to manage your subscription! But knowing what we know right now, I don't think it's worth the inconsistency of maintaining two versions of the header component (one on the `/payments/thank-you` page and one on the `/payments` page (showing a link in one but not the other).

**Comment by peterbe** [comment]
So, apart from deep down in the FAQ and the the "Edit Profile", how are you supposed to return to your subscription later? 
Also, really really hope that having the Stripe integration on the Subscription landing page (aka. Payments index page, aka. FAQ page) is going to be the ONLY place where there's Stripe integration, that means it's even more unlikely that subscribers will discover it at the bottom of the Edit Profile page.

**Comment by malqinneh** [comment]
> how are you supposed to return to your subscription later?

Getting/having the answer to **why** users are looking to return to their subscription would be a good place to start. Ultimately there are a lot of ways of solving a problem but not without having a solid understanding of the problem.

**Comment by chinikes** [comment]
Hi @atopal, @peterbe , @malqinneh  - With #6567 in review, can we verify that the ACs of this story have been met at this point?

**Comment by peterbe** [comment]
No, I think this depends on https://github.com/mdn/kuma/pull/6825 still.

**Comment by atopal** [comment]
That's correct.
