### ISSUE TITLE
U - As a potential subscriber I want the option to log in during the payment process, so I don't have to navigate the page for that

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6557]
# Acceptance Criteria
- [x] not-signed-in users who click "Learn more" on the banner are taken to the FAQ page.
- [x] not-signed-in users who click "continue" on the FAQ page are shown the sign-in overlay with specific text about supporting MDN.
- [x] After they are authenticated, users are taken to the FAQ page.
- [x] The banner is behind a waffle flag, so we can turn it on and off for non-logged in users as necessary.

# Context
The goal is to give people who weren't signed in at the time they clicked the "subscribe" button an option to sign in without taking them out of the payment flow.

# Design

- Signed in user:
 https://share.goabstract.com/857f8a74-8fdd-41e6-9d78-d5c838d4054a?mode=design
- **Non-signed in users (but with an account):** 
 https://share.goabstract.com/857f8a74-8fdd-41e6-9d78-d5c838d4054a?collectionLayerId=1c005660-47c6-4d98-aac5-bc533fa9ae26&mode=design
- Non-signed in users (without an account): 
https://share.goabstract.com/857f8a74-8fdd-41e6-9d78-d5c838d4054a?collectionLayerId=0083a875-bdc1-49e2-9215-9a0c59a4cab6&mode=design
- And then the specific use-case where you have the banner take you to the user profile/settings page(?): https://share.goabstract.com/80aff1b8-a8da-4250-ab33-f6426d45b2e1?mode=design

**Comment by tobinmori** [comment]
Some questions for @atopal @malqinneh :

**Re: "Registered MDN User, logged in/Non-MDN user, not logged-in" modal**

- What specific event(s) trigger this modal? 
- The messaging is a bit confusing here in that these sound more like a statements of one's logged-in status, rather than a CTA
- Where does the user land upon clicking either option?

**Comment by atopal** [comment]
@tobinmori not sure what modal you mean? There is no modal in this flow. This is for when a non-logged in users clicks "subscribe" on the payments banner.

**Comment by chinikes** [comment]
@schalkneethling , @atopal , @tobinmori - This story has been marked done on the spreadsheet. Can you confirm the ACs have been met? Thanks!

**Comment by chinikes** [comment]
Hi @tobinmori - this story doesn't have any tasks set up to implement it although it's in the current sprint. Is the Team considering taking it out of the sprint / rolling over to Delta? If so we'll need the story "tasked out" in time before delta's planning session

**Comment by tobinmori** [comment]
@tobinmori 

Tasks:
- autho modal needs to be callable from anywhere. (1) (from Continue link)
- have 'next' redirect to Stripe modal (if user has to go thru signup flow)

**Comment by peterbe** [comment]
>     * not-signed-in users who click "continue" on the FAQ page are shown the sign-in overlay with specific text about supporting MDN.

@atopal @malqinneh Can you expand on that a bit? 
The design looks like this:
<img width="932" alt="Screen Shot 2020-03-26 at 2 56 49 PM" src="https://user-images.githubusercontent.com/26739/77685638-1c4d3c00-6f72-11ea-969d-dbbb1fa89168.png">

Not that users ever read texts but that text there the same text you get before the two identity providers we have in our current auth modal. 

If you want to, I think I can expand https://github.com/mdn/kuma/pull/6749 so that triggering the auth modal from different places trigger different texts within the modal. 
For example, if you click the "Sign in" on any other page, in the upper right-hand corner it is the text it currently is today. 
But if you clicked the "Continue ->" button the Subscription landing page, and you're not signed in, we can append/replace a different message. Like "Hey! Before you crack open that sweet credit card diggies, let's sign in first and then you can come here. Ok?"

**Comment by malqinneh** [comment]
> Not that users ever read texts but that text there the same text you get before the two identity providers we have in our current auth modal.

The original copy of the *current* auth modal is:
`Sign in to enjoy the benefits of an MDN account. If you haven't already created an account, you will be prompted to do so after signing in.`

<img width="526" alt="Screen Shot 2020-03-26 at 4 17 12 PM" src="https://user-images.githubusercontent.com/4819906/77692705-7c95ab00-6f7d-11ea-8497-dde4a81be0fd.png">

For visitors that click support MDN without being logged in, the auth modal copy should read:
`Sign in to support MDN. If you haven't already created an account, you will be prompted to do so after signing in.`

However, we can simplify this and keep the same copy for all auth modal prompts - regardless where/how they are activated (assuming it significantly reduces engineering complexity). In that case, I would simplify the copy to read:
`If you haven't already created an account, you will be prompted to do so after signing in.`

**Comment by chinikes** [comment]
Hi @atopal, @peterbe , @tobinmori - With all associated tasks closed, can we verify that the ACs of this story have been met at this point?

**Comment by peterbe** [comment]
> Hi @atopal, @peterbe , @tobinmori - With all associated tasks closed, can we verify that the ACs of this story have been met at this point?

No, because the way I implemented does perfectly match how @malqinneh and @atopal presented the wireframes to Mozilla Legal. In my implementation, if you've checked the checkbox and had to sign in, after you come back to the Subscription landing page, it would "auto-check the checkbox" for you. 
So @malqinneh and @atopal are going to verify that this is an OK implementation. If it's not, we'll add another task to this issue about reverting part of that functionality.

**Comment by atopal** [comment]
@peterbe we have the go-ahead from our legal counsel. :+1
