### ISSUE TITLE
U - As a potential subscriber I want the option to create an account as part of the payment process, so I don't have to do that separately

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6558]
# Acceptance Criteria
- [x] Not-signed-in users who click "more info" on the banner are taken to the FAQ page.
- [x] Not-signed-in users who click "continue" on the FAQ page are shown the sign-in overlay with specific text about supporting MDN.
- [x] After they are authenticated, they are asked to create an account, if they don't already have an MDN account.
- [x] After they have created an account they are taken to the FAQ page.

# Context
The goal is to give people who weren't signed in at the time they clicked the "subscribe" button an option to sign in without taking them out of the payment flow.

# Design

- Signed in user:
 https://share.goabstract.com/857f8a74-8fdd-41e6-9d78-d5c838d4054a?mode=design
- Non-signed in users (but with an account): 
 https://share.goabstract.com/857f8a74-8fdd-41e6-9d78-d5c838d4054a?collectionLayerId=1c005660-47c6-4d98-aac5-bc533fa9ae26&mode=design
- **Non-signed in users (without an account):** 
https://share.goabstract.com/857f8a74-8fdd-41e6-9d78-d5c838d4054a?collectionLayerId=0083a875-bdc1-49e2-9215-9a0c59a4cab6&mode=design
- And then the specific use-case where you have the banner take you to the user profile/settings page(?): https://share.goabstract.com/80aff1b8-a8da-4250-ab33-f6426d45b2e1?mode=design

**Comment by tobinmori** [comment]
I think the questions I posted in #6557, pertain here.

**Comment by chinikes** [comment]
Hi @tobinmori - this story doesn't have any tasks set up to implement it although it's in the current sprint. Is the Team considering taking it out of the sprint / rolling over to Delta? If so we'll need the story "tasked out" in time before delta's planning session

**Comment by tobinmori** [comment]
We get this functionality 'for free' - so there should be no other tasks needed for this as it stands.

**Comment by chinikes** [comment]
Hi @atopal, @peterbe , @tobinmori - With all associated tasks closed, can we verify that the ACs of this story have been met at this point?

**Comment by atopal** [comment]
#6837 needs to be verified.
