### ISSUE TITLE
U - As a logged in user, I want the option to pay in place, so I don't have to go my profile

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6559]
# User story
As a logged in user, I want the option to pay in place, so I don't have to go my profile

# Acceptance criteria

- [ ] Logged in users  who click on subscribe in the banner see a modal to become monthly subscribers
- [ ] Modal is only shown on desktop
- [ ] model has checkbox to verify that user wants to become a subscriber
- [ ] Text in modal is identical to design for legal reasons
- [ ] If user clicks subscribe in modal without having checked the box, an error message is shown
- [ ] If the checkbox is checked and the user clicks on subscribe, a stripe modal is shown
- [ ] If they successfully completes the stripe modal, they are taken to the dedicated thank you page
- [ ] Users can cancel the payment modal at any time by clicking on the x in the upper right corner, which dismisses the modal

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

# Context
In #6554 we already implemented the banner for logged in users and redirected to the profile to have a full end to end payment experience. This should add the modal to pay in place for logged in users, so they don't have to go to the profile and get a full thank you page.

**# Design

- Signed in user:
 https://share.goabstract.com/857f8a74-8fdd-41e6-9d78-d5c838d4054a?mode=design
- Non-signed in users (but with an account): 
 https://share.goabstract.com/857f8a74-8fdd-41e6-9d78-d5c838d4054a?collectionLayerId=1c005660-47c6-4d98-aac5-bc533fa9ae26&mode=design
- Non-signed in users (without an account): 
https://share.goabstract.com/857f8a74-8fdd-41e6-9d78-d5c838d4054a?collectionLayerId=0083a875-bdc1-49e2-9215-9a0c59a4cab6&mode=design
- And then the specific use-case where you have the banner take you to the user profile/settings page(?): https://share.goabstract.com/80aff1b8-a8da-4250-ab33-f6426d45b2e1?mode=design**

**Comment by tobinmori** [comment]
@atopal do we need to store the fact that the user clicked the checkbox (as data)? or does clicking the checkbox simply let them see the stripe payment modal?:

"model has checkbox to verify that user wants to become a subscriber"

**Comment by atopal** [comment]
@tobinmori We don't need to store the fact, it should not be possible to submit without that checkbox being checked. That is: an error message is shown when the button is clicked without the checkbox being checked. That is because it can be frustrating to have an inactive button without understanding why. Better to tell them what to fix when they miss it.

**Comment by tobinmori** [comment]
task #6578

**Comment by atopal** [comment]
During sprint planning for Charlie, we decided to eliminate this user story. Everyone clicking on "subscribe" on the banner will be taken to the FAQ page. We can reactivate this user story for optimization purposes in the future.
