### ISSUE TITLE
U - As the MDN PM I want to show people a dedicated thank you page, so we can thank them and get their feedback

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6560]
# User story
As the MDN PM I want to show people a dedicated thank you page, so we can thank them and get their feedback

# Acceptance criteria

- [x] Thank you page displays text as designed
- [x] Thank you page links to terms
- [x] Thank you page links to a way to cancel
- [x] Thank you page links to the FAQ
- [x] Users can give feedback using the form on the page
- [x] Feedback goes to Google Analytics
- [x] Upon sending the feedback, the text field is disabled.
- [x] Upon sending feedback, the line "Thank you for submitting your feedback" appears below text field.

# Tasks

1. - [ ] [Convert Subscription 'Thank You' Page to React](https://github.com/mdn/kuma/issues/6581) 

# Context
This page is shown after the stripe modal has completed

# Design

- Signed in user:
 https://share.goabstract.com/857f8a74-8fdd-41e6-9d78-d5c838d4054a?mode=design
- Non-signed in users (but with an account): 
 https://share.goabstract.com/857f8a74-8fdd-41e6-9d78-d5c838d4054a?collectionLayerId=1c005660-47c6-4d98-aac5-bc533fa9ae26&mode=design
- Non-signed in users (without an account): 
https://share.goabstract.com/857f8a74-8fdd-41e6-9d78-d5c838d4054a?collectionLayerId=0083a875-bdc1-49e2-9215-9a0c59a4cab6&mode=design
- And then the specific use-case where you have the banner take you to the user profile/settings page(?): https://share.goabstract.com/80aff1b8-a8da-4250-ab33-f6426d45b2e1?mode=design

**Comment by tobinmori** [comment]
task #6581

**Comment by mindy** [comment]
@atopal Regarding this acceptance criteria: "Upon sending the feedback, the text field is disabled.", can you help me understand why we want to limit a user's feedback by disabling the text field after submission? I think that we should not discourage them from submitting feedback if they had an afterthought, for example.

**Comment by atopal** [comment]
Mindy, it's to signal users that submitting has worked. I'd be pretty surprised if after submitting a message my original message still showed up. The idea is to grey it out once done.

**Comment by mindy** [comment]
Thanks Kadir. If that's the case, I think there are other ways to indicate that submitting has worked, without disabling the input (this came up in code review and we thought it was strange):
1.  "Thank you" message and clearing the form input after submission.
2. "Thank you" message and hiding the form entirely after submission (thanks to Peter for the suggestion). 

Option 1 is what I originally built, so it's not hard to revert to that version. 
Option 2 is what we settled on.

**Comment by atopal** [comment]
I don't feel strongly about this, but I personally like seeing what I just submitted, and disabling seemed like the simplest option. If you feel strongly about it, feel free to go with option 2.

**Comment by chinikes** [comment]
Hi @mindy - Wanted to follow up on the outstanding acceptance criteria. Has it been met at this point?

**Comment by mindy** [comment]
Hi @chinikes, 

Yes, we modified the acceptance criteria and went with the option described above: "Thank you" message and hiding the form entirely after submission," instead of disabling the text field as originally planned. 

Below are screenshots of the feedback form.

Screenshot of min character length error: 
<img width="1133" alt="Screen Shot 2020-04-07 at 11 09 22 AM" src="https://user-images.githubusercontent.com/650/78686070-99f14000-78c0-11ea-8dbb-bab3bb8384a9.png">

After submission: 
<img width="1135" alt="Screen Shot 2020-04-07 at 11 09 48 AM" src="https://user-images.githubusercontent.com/650/78686073-9a89d680-78c0-11ea-899a-d55efede5eb1.png">

Server error: 
<img width="1056" alt="Screen Shot 2020-04-07 at 11 11 27 AM" src="https://user-images.githubusercontent.com/650/78686074-9b226d00-78c0-11ea-8595-c46326ff59bf.png">

**Comment by chinikes** [comment]
Thanks @mindy 

@atopal - Can this user story be verified as done at this point?
