### ISSUE TITLE
T - Create Stripe webhook handler for sending email receipt to Customer

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6562]
**Description**

Upon a successful payment event in Stripe, and subsequent handled webhook event, send an email receipt from Kuma.

**Tasks**
- [ ] setup a test/stage webhook event in Stripe so that upon successful Customer payment a webhook is triggered (ask Tobin if you need help with this)
- [ ] in Kuma, create a webhook handler that sends an email receipt to the Customer's email address. NOTE: we're still waiting to determine whether this will be a text or HTML email (and final copy)
- [ ] email text should read: "Cancel any time. To cancel your subscription, please [contact support]. If you have questions, please read the [FAQ] or you can also contact support."
- [ ] make sure webhook is coming from Stripe :)
- [ ] write tests

**Docs**
https://stripe.com/docs/recipes/sending-custom-email-receipts

**Comment by atopal** [comment]
Let's make this one about the text only version.

**Comment by Gregoor** [comment]
>  email text should read: "Cancel any time. To cancel your subscription, please [contact support]. If you have questions, please read the [FAQ] or you can also contact support."

No link to the payment management page?

**Comment by atopal** [comment]
Good point, since we have that now, we can update the text. 

"Cancel any time. To cancel your subscription, please go to the [manage monthly subscriptions page]. If you have questions, please read the [FAQ] or you can also [contact support]."

**Comment by chinikes** [comment]
Hi @Gregoor , @tobinmori - what user story is this task implementing? I'm assuming it needs to be done to complete the epic?

**Comment by tobinmori** [comment]
correct @chinikes
