### ISSUE TITLE
T - Convert Subscription 'Thank You' Page to React

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6581]
## 💬 Description
Update design, content, and functionality for Subscription "Thank You" page and convert to React. Current version is here: https://wiki.developer.mozilla.org/en-US/payments/recurring

## 👷‍♀ Tasks
- [x] Add route and view in Django for Thank You page 
- [x] Create React component for Thank You page
- [x] Create feedback form which, upon submission, records feedback by sending a GA event 

## 🎨 Design
https://mozilla.invisionapp.com/share/TDVED747SB9#/screens/399165369

**Comment by schalkneethling** [comment]
Hey @mindy,

The information here will apply to both the work here as well as the work on the FAQ so, this will be a central location for reference. Hope you find this useful.

As @escattone mentioned on Slack, there is a utility[1] that determines whether we are on the wiki or read-only site, and based on that, either load the wiki or React based document[2] for the documentation pages.

For quick reference here are the two places in the codebase referenced to above:

[1] https://github.com/mdn/kuma/blob/e9fa3ec4c70a8cbcf31e62706dc05cf6aaa1ddfa/kuma/core/utils.py#L45
[2] https://github.com/mdn/kuma/blob/e9fa3ec4c70a8cbcf31e62706dc05cf6aaa1ddfa/kuma/wiki/views/document.py#L660

For the "thank you" and "FAQ" pages everything will be React and so, these pages will be what is known as a `SPA(SinglePageApp)` component. https://github.com/mdn/kuma/blob/074250459d0425c96158bec6e2e37c59f2a7efb0/kuma/javascript/src/index.jsx#L32 and here https://github.com/mdn/kuma/blob/074250459d0425c96158bec6e2e37c59f2a7efb0/kuma/javascript/src/ssr.jsx#L45

Before we get to that however we need to get some things set-up in Django. Seeing that we do not currently have a dedicated "Thank you" page, you would need to add a new `url` and `view`

The `url` would be defined in https://github.com/mdn/kuma/blob/074250459d0425c96158bec6e2e37c59f2a7efb0/kuma/payments/urls.py#L6

```
url(r"^recurring/thank-you?$", views.thank_you, name="thank_you"),
```

The `view` will go in https://github.com/mdn/kuma/blob/074250459d0425c96158bec6e2e37c59f2a7efb0/kuma/payments/views.py

```
@skip_if_disabled
@ensure_wiki_domain
@never_cache
def thank_you(request):
    return render(request, "payments/thank_you.html")
```

Because this will only be active on the read-only site, we do not have to worry about the `is_wiki` utility and can just point to the base HTML for the React page.

In the new `thank_you.html` page you can start by duplicating some of the pieces from a page such as https://github.com/mdn/kuma/blob/074250459d0425c96158bec6e2e37c59f2a7efb0/kuma/payments/jinja2/payments/terms.html#L1

I would recommend that you begin with as little as possible and then add things as you find pieces missing.  This is then also where you would include the call to `render_react`: https://github.com/mdn/kuma/blob/074250459d0425c96158bec6e2e37c59f2a7efb0/kuma/wiki/templatetags/ssr.py#L24

```
{% extends 'react_base.html' %}

{% block title %}{{ page_title(_('Thank You')) }}{% endblock %}

{{ render_react("SPA", request.LANGUAGE_CODE, request.get_full_path(),
                None, False)|safe }}
```

In `kuma/javascript/src` you can then add the page component `thank-you-page.jsx`. Here is a skeleton as a starting point:

```
// @flow
import * as React from 'react';

import { gettext } from './l10n.js';
import A11yNav from './a11y/a11y-nav.jsx';
import Banners from './banners.jsx';
import Header from './header/header.jsx';
import UserProvider from './user-provider.jsx';
import Route from './route.js';

type ThankYouRouteParams = {
    locale: string
};

export default function ThankYouPage() {
    return (
        <>
            <UserProvider>
                <A11yNav />
                <Header />
                <Banners />
                <Newsletter />
                <Footer />
            </UserProvider>
        </>
    );
}

// In order to use new URL() with relative URLs, we need an absolute base
// URL. If we're running in the browser we can use our current page URL.
// But if we're doing SSR, we just have to make something up.
const BASEURL =
    typeof window !== 'undefined' && window.location
        ? window.location.origin
        : 'http://ssr.hack';

export class ThankYouRoute extends Route<ThankYouRouteParams, null> {
    locale: string;

    constructor(locale: string) {
        super();
        this.locale = locale;
    }

    getComponent() {
        return ThankYouPage;
    }

    match(url: string): ?ThankYouRouteParams {
        let path = new URL(url, BASEURL).pathname;

        if (path !== `/${this.locale}/payments/thank-you`) {
            return null;
        }

        return {
            locale: this.locale
        };
    }

    fetch() {
        return Promise.resolve(null);
    }

    getTitle() {
        return `${gettext('Thank You')} | MDN`;
    }
}

```

You also need to tell the `single-page-app` component about our new `Route` handler: https://github.com/mdn/kuma/blob/074250459d0425c96158bec6e2e37c59f2a7efb0/kuma/javascript/src/single-page-app.jsx

```
import { ThankYouRoute } from './thank-you-page.jsx';
```

and then at https://github.com/mdn/kuma/blob/074250459d0425c96158bec6e2e37c59f2a7efb0/kuma/javascript/src/single-page-app.jsx#L20

```
const routes = [
    new DocumentRoute(locale),
    new SearchRoute(locale),
    new ThankYouRoute(locale)
];
```

With this you will notice that the page renders two footers :) That is because the `footer` in `react_base.html` currently does not wrap the `footer` element inside a `block` and we can therefore not override it.

I would, therefore, recommend that you also fix this as part of the work here, for example in `react_base.html`:

```
{% block footer %}
<!-- Footer -->
<footer id="nav-footer" class="nav-footer">
...
{% endblock %}
```

The in `thank-you.html` you can add the following so the footer from `react_base` is not included:

```
{% block footer %}{% endblock %}
```

I hope this helps you get started and answers some of the questions you may have. I would also highly recommend that you click around on the different pieces such as `Route`, `SinglePageApp` etc. and read the amazing comments that @davidflanagan added to all of this. It is invaluable.

I would also appreciate if @Gregoor and @peterbe can have a peek at the above and add any additional guidance I may have overlooked.

**Comment by schalkneethling** [comment]
One thing I did notice is that with the skeleton as it as above, the loading strip at the of the page keeps animating. I am assuming it has something to do with the fact that this page will not actually need to do any `fetch`ing simply does:

```
fetch() {
   return Promise.resolve(null);
}
```

I did that based on David's comment here:
https://github.com/mdn/kuma/blob/074250459d0425c96158bec6e2e37c59f2a7efb0/kuma/javascript/src/route.js#L50

A couple of lines down from the above there is also this comment which might be related:

```
// TODO: update Router to handle the null return case
```

**Comment by mindy** [comment]
@atopal Two things I need from you: 
1. Can you provide the following values for the GA event that we are using to collect user feedback: `eventCategory`, `eventAction`, `eventLabel` (optional), `eventValue`  (optional), `fieldsObject` (optional)? 
2. What should the url be? Do we keep as is (`/payments/recurring`) or change it to something more accurate like `/payments/thank-you`?

**Comment by atopal** [comment]
> @atopal Two things I need from you: 
>     1. Can you provide the following values for the GA event that we are using to collect user feedback: `eventCategory`, `eventAction`, `eventLabel` (optional), `eventValue`  (optional), `fieldsObject` (optional)?

eventCategory: monthly payments
eventAction: feedback
eventLabel: thank you page

**Comment by mindy** [comment]
@atopal wanted to double-check-- for `eventAction: feedback`, did you mean literally "feedback" or the feedback from the text input that the user submits?

**Comment by atopal** [comment]
ah, sorry, I mixed things up here.

eventCategory: monthly payments
eventAction: feedback
event label: [feedback]

where [feedback] is the content of the user input

**Comment by peterbe** [comment]
This broke the Subscription landing page (`payments/index.jsx`) and [we didn't notice](https://github.com/mdn/kuma/issues/6790).

**Comment by atopal** [comment]
Something is really off here. Why does the FAQ page live under payments/thank-you that must be a misunderstanding. The thank you page is for after you have made a payment. @tobinmori

**Comment by atopal** [comment]
Sorry, I might just be misunderstand this, maybe payments/thank-you is what you see after making a payment and we redirect to /payments unless you just made a payment? Unfortunately I can't test this on staging right now, seeing a server error when I try to make a payment.

**Comment by mindy** [comment]
@atopal Staging has not been updated yet, so I wonder if that is why you're seeing the FAQ page when you visit /payments/thank-you. The FAQ page is the catch-all for all /payments urls. 

> Sorry, I might just be misunderstand this, maybe payments/thank-you is what you see after making a payment

From looking at Gregor's PR (https://github.com/mdn/kuma/pull/6756/files#diff-080e1355199ea13fb9622eeb99f083fdR115), I believe that is what will happen once it is merged in.

**Comment by peterbe** [comment]
Yeah, when @Gregoor 's PR is ready, the `/$locale/payments` will be the FAQ (plus the subscription form at the top) and `/$locale/payments/thank-you` page is just that, a thank you page. 
It's worth noting that you can come back to the thank you page at any time by simply typing in the URL. So we have to be cognizant with the fact that just because you're on that page, it doesn't necessarily imply that you've *just* become a subscriber. It's a public page, backed by the API.

**Comment by atopal** [comment]
Thanks for clearing this up, was thrown by /thank-you showing the landing page. All good!
