### ISSUE TITLE
T - Create landing page (FAQ) for Subscriptions

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6582]
## 💬 Description
Create a landing page for Subscriptions in React, so we can reuse components. The page will live at /payments. 

## ✅ Acceptance Criteria
- [ ] User can navigate to /payments page
- [ ] User can read FAQ about why we are doing this and what to expect 
- [ ] User viewing on a smaller screen does not have a terrible experience

_Note: The "Help grow MDN" callout in the header is **not** expected to be completed during this sprint_
 
## 👷‍♀ Tasks
- [x] Add a new route and view in Django for /payments
- [x] Create React component, borrowing content from existing [Thank You page](https://wiki.developer.mozilla.org/en-US/payments/recurring)
- [x] Update copy to match what's in [latest copy edits](https://docs.google.com/document/d/1TH-P-hcZY1UzBtXDGGZnF3jTCy7b-cgC3TUo4Vwxfdc/edit?usp=sharing )

## 🎨 Design
https://app.abstract.com/projects/9decc480-70fc-11e9-9453-4f3fbffea7ce/branches/master/commits/5eb3004bb0e0aeb362aae44b3da2fa7d15d893cb/files/96E76C7B-2AF8-4473-A39E-E81890F91955/layers/0A8C3971-7D07-40BF-96B5-3B467D450CC4?mode=build&selected=734966551-1AF136E1-5788-4D35-A3CF-0E452D009A7B

~~https://mozilla.invisionapp.com/share/TDVED747SB9#/screens/399165366~~

## 🔦 Context
Please see Schalk's comment https://github.com/mdn/kuma/issues/6581#issuecomment-591376908

**Comment by mindy** [comment]
Task 1: Move content from the existing "Thank You" page (https://wiki.developer.mozilla.org/en-US/payments/recurring) to a new FAQ page. 

@atopal Do you have a url preference for the FAQ page? Perhaps `/payments/faq`?

**Comment by atopal** [comment]
How about just /payments?

**Comment by mindy** [comment]
/payments sounds good. I had thought of this page as the "FAQ" page, but this naming implies that it will essentially the landing page for payments, which is helpful for me to know.
