### ISSUE TITLE
KR - l10n plan for Yari complete

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#6643]
# Context
As part of the move to Yari we have to make some explicit decisions about L10n. Since we can't just continue as before, we need an L10n strategy, if we don't want to make ad-hoc decisions. We'll have to answer the following questions before we can really make tooling decisions:

* Do we move forward with L10n or not? (Why do we do L10n?)
* If yes,
    * Do we use automated L10n, manual L10n or something in between?
        * If we go with manual L10n:
            * Do we work with professionals, volunteers or both?
            * Do we support all locales or a subset?
            * What does the workflow look like for those localizers

Once we have made a decision, it needs to be documented and communicated. After that, we need a plan to execute the decision.

# Acceptance Criteria 
- [x] Riskiest assumptions identified
- [ ] Riskiest assumptions researched
- [ ] Document that clarifies our goals with L10n, guiding principles and the reason for our decision making

# Additional Context
We are looking at the items with the highest amount of unknowns and trying to de-risk by reducing uncertainty.

**Comment by peterbe** [comment]
> we have a pretty good idea of what state of art online l10n is

that's huge :)

It scares me that this is called a "mitigation" as mitigations are usually about making big/risk change smaller and safer. 
Understanding the full potential of machine learning automation (aka. "state of the art") and how it could be leveraged in Yari 1 is a massive task. And suppose that we *do* find out that there's an cloud API we can use to automate translations from English to $locale, then what are we going to do with that knowledge? Incorporate it into the Yari 1 migration?

**Comment by chinikes** [comment]
@atopal - Wanted to confirm what AC item you want knocked out during sprint delta?

**Comment by atopal** [comment]
@chinikes probably the first two ACs in here.
