### ISSUE TITLE
U - As a developer who wants to move content from MySQL to  Github, I need a tool that renders Kumascript in raw HTML pages using metadata provided by Github. 

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6661]
### Summary
When MDN moves into GitHub, many if not all of the documents will still contain embedded Kumascript macros. As part of the process of rendering each document's raw HTML into a finished HTML page, we first need to be able to render the macros within each document's raw HTML. So this Epic is concerned with that goal.

### Acceptance Criteria
- [x] Can successfully render, via a Node CLI, the **/en-US/docs/Web/HTML** document using the existing Kumascript API.
- [x] The `subpages` API function has been implemented and tested.
- [x] The `subpagesExpand` API function has been implemented and tested.
- [x] The `translations` API function has been implemented and tested.
- [ ] Evaluate next steps and task them out if needed. 

### Tasks
- [x] Create a Node command that can take each document's raw HTML and render all of the embedded Kumascript macros using the **existing** Kumascript API calls (which use the network to make calls to https://developer.mozilla.org). This simply ensures the basic framework is in place as part of a Node CLI command. It leaves the much more difficult work, that of actually replacing the existing Kumascript API with a "shim" that gets its information from the documents within the `yari` GitHub repo itself rather than from https://developer.mozilla.org, as a next step. This work includes deciding how to incorporate the actual Kumascript macro files into the repo (since they'll probably have to be modified, we will perhaps have to include our own versions of them directly within the `yari` repo?). (https://github.com/mdn/kuma/issues/6666)
- [x] Implement the `subpages`, `subpagesExpand`, and `translations` API functions called by many macros (these are key parts of the Kumascript API Shim). (https://github.com/mdn/kuma/issues/6667)
- [ ] After completing the above, use the insight gained to add the additional tasks needed to complete this epic.
