### ISSUE TITLE
E - Prototype KumaScript Rendering Tool

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6675]
### Summary
When MDN moves into GitHub, many if not all of the documents will still contain embedded Kumascript macros. As part of the process of rendering each document's raw HTML into a finished HTML page, we first need to be able to render the macros within each document's raw HTML. So this Epic is concerned with that goal.

### Acceptance Criteria
- [x] Can successfully render, via a Node CLI, the **/en-US/docs/Web/HTML** document using the existing Kumascript API.
- [x] The `subpages` API function has been implemented and tested.
- [x] The `subpagesExpand` API function has been implemented and tested.
- [x] The `translations` API function has been implemented and tested.
- [x] The `getPage` API function has been implemented and tested.
- [x] The `page` API function has been implemented and tested.
- [x] Explore solutions for handling live code samples and document the selected solution. The solution should allow us to successfully render the `EmbedLiveSample` macro.
- [x] The `EmbedLiveSample` macro can be successfully rendered.
