### ISSUE TITLE
U - As a monthly subscriber I want a receipt email, so I can see what charge to expect on my credit card

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6719]
# User Story
As a monthly subscriber I want a receipt email, so I can see what charge to expect on my credit card

# Acceptance Criteria
- [x] Email design that clearly communicates that people are going to be charge for their MDN subscription
- [x] legally required context is considered
- [x] email design works with gmail and outlook

**Comment by atopal** [comment]
Here's what the email currently looks like:

Hello from MDN!

https://pay.stripe.com/invoice/acct_1D9vONFBqYLAtsSt/invst_GvwAyiyWDg41zL58jjm72nr1O9RFQyC/pdf

Cancel any time. To cancel your subscription, please go to the manage monthly subscriptions page: https://developer.mozilla.org/en-US/payments/recurring/management.
If you have questions, please read the FAQ (https://developer.mozilla.org/en-US/payments/recurring/subscription) or you can also contact support: mdn-support@mozilla.com

Thank you for using MDN!

**Comment by atopal** [comment]
This is what the Stripe receipt looked like:
![Alle_Postfächer__Die_Suche_ergab_148_Treffer_-_Verbindungsprotokollierung_aktiviert_](https://user-images.githubusercontent.com/557852/77335314-490d1380-6d26-11ea-9e3a-f451d63e3b20.png)

**Comment by atopal** [comment]
What has to be in the email:

Amount charged
Date
Payment Method
Next Recurring Date
Cancellation Policy
How to Cancel

**Comment by malqinneh** [comment]
Spoke with Kadir:

First iteration of this will be a text only version that includes all information (from receipt and legal obligation). Second iteration will be optimizing the design for a better UX.

**Comment by malqinneh** [comment]
@atopal how is this for a first pass: https://docs.google.com/document/d/1Gx-2cniZlWTPhsbYBNJj7n36lmnvPZ-vNEFOoAA5ksQ/edit?usp=sharing

**Comment by tobinmori** [comment]
@atopal @malqinneh - any formatting increases the work here. 

Essentially, the problems with this are:
- no bold
- no links (URLS ok)
- no table

Can we simply this further?

**Comment by malqinneh** [comment]
> @atopal @malqinneh - any formatting increases the work here.
> 
> Essentially, the problems with this are with text the following are not possible:
> 
>     * no bold
> 
>     * no links (URLS ok)
> 
>     * no tables
> 
> 
> Can we simply this further? If we can simply this so that it's just text - it would be a 1 estimate.

Yes, please check the link again to see simplified version at the top of the page.

**Comment by chinikes** [comment]
Hi @atopal, @Gregoor , @malqinneh  - With all associated tasks closed, can we verify that the ACs of this story have been met at this point?

**Comment by Gregoor** [comment]
looks good in both gmail and outlook (web)
