### ISSUE TITLE
E- Riskiest L10n assumptions tested and reported

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6736]
# Accpetance Criteria
- [x] identified assumptions tested where possible
- [x] assumptions planned for testing where necessary
- [ ] decision on whether we are done or need more assumptions tested before we can draft our strategy doc

# Context
## Assumptions
- [ ] Automated translation is effective enough to be useful to us
- [ ] If we don't support L10n, we'll see a massive drop in task completion
- [ ] Doing localization will give us enough new users to be worth it.
- [ ] People are mostly solving L10n with the built in feature of Chrome, and it's good enough
- [ ] There are solutions out there, so we don't have to build our own tools

**Comment by chinikes** [comment]
Epic closed based on updated scope of Yari implementation
