### ISSUE TITLE
U - Optimize Breadcrumbs and footer for mobile

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#6784]
# User Story 
As a user, I want an Optimized Breadcrumbs, header and footer for mobile so that I can have a better experience using MDN on mobile 

# Design 

**Header**
- [Mobile](https://share.goabstract.com/ef1e325d-f6b5-4059-92e2-01634d792eb8?mode=design)
![Header - Mobile - Light](https://user-images.githubusercontent.com/4819906/79573164-315a4e00-808c-11ea-82b7-86dfc6bab7c6.png)

- [Tablet](https://share.goabstract.com/ef1e325d-f6b5-4059-92e2-01634d792eb8?mode=design) 
![Header - Tablet - Light](https://user-images.githubusercontent.com/4819906/79573172-35866b80-808c-11ea-804f-ad683b99136e.png)

- [Desktop](https://share.goabstract.com/ef1e325d-f6b5-4059-92e2-01634d792eb8?mode=design)
![Header - Desktop - Light](https://user-images.githubusercontent.com/4819906/79573189-38815c00-808c-11ea-8062-81543f561b87.png)

**Footer**
- [Mobile](https://share.goabstract.com/ef1e325d-f6b5-4059-92e2-01634d792eb8?mode=design)
![Footer - Mobile - Light](https://user-images.githubusercontent.com/4819906/79573305-71213580-808c-11ea-94f7-5a604910b278.png)

- [Tablet](https://share.goabstract.com/ef1e325d-f6b5-4059-92e2-01634d792eb8?mode=design)
![Footer - Tablet - Light](https://user-images.githubusercontent.com/4819906/79573312-754d5300-808c-11ea-84bf-15cde717620a.png)

- [Desktop](https://share.goabstract.com/ef1e325d-f6b5-4059-92e2-01634d792eb8?mode=design)
![Footer - Desktop - Light](https://user-images.githubusercontent.com/4819906/79573316-77171680-808c-11ea-9f0d-cac7d833cfd1.png)

**Breadcrumb**
- [Mobile](https://share.goabstract.com/ef1e325d-f6b5-4059-92e2-01634d792eb8?mode=design)
![Breadcrumb - Mobile - Light](https://user-images.githubusercontent.com/4819906/79573436-a594f180-808c-11ea-8019-42044aec162e.png)

- [Tablet](https://share.goabstract.com/ef1e325d-f6b5-4059-92e2-01634d792eb8?mode=design)
![Breadcrumb - Tablet - Light](https://user-images.githubusercontent.com/4819906/79573443-a9c10f00-808c-11ea-81d2-c0ea72287731.png)

- [Desktop](https://share.goabstract.com/ef1e325d-f6b5-4059-92e2-01634d792eb8?mode=design)
![Breadcrumb - Desktop - Light](https://user-images.githubusercontent.com/4819906/79573446-ac236900-808c-11ea-8a69-022b5b778c46.png)

# Acceptance Criteria 
- [ ] New responsive footer implemented on desktop, tablet, mobile
- [ ] New attribute-based breadcrumb implemented on mobile (only)
- [ ] [Instrumentation](https://docs.google.com/spreadsheets/d/1plvnK5gBcrpmSwVwaVMFVvPK8ihrDL4LzObhZOtlj2Y/edit?usp=sharing) on [tap] events - desktop instrumentation is on [hover] events, need to make sure we register the same events for [tap]

**Comment by tobinmori** [comment]
@atopal @malqinneh is this for read-only site only? or including wiki?

**Comment by atopal** [comment]
@tobinmori Only the read-only site

**Comment by schalkneethling** [comment]
@malqinneh I just noticed the language selector in the footer. We removed it in the past from the /docs/ pages as there is an alternate option in the head section of those pages. Is the intent to add the language selector back or, should we go ahead and standardize on a footer without a language selector?

See the footer here for example:
https://developer.mozilla.org/en-US/docs/Web/JavaScript

**Comment by malqinneh** [comment]
@schalkneethling thank you for bringing this up, my recommendation is that we should include it across all footers until we have better info from our L10n research/studies. But why did we decide to remove it from the footer if there is an alternate option in the head section? Technical constraint for having two components doing the same thing?

From a UX perspective, some people look for language selectors in the footer (even though they might be elsewhere on the page). From a Google indexing perspective, it might be beneficial for keeping traffic up. From a design systems perspective, unless there is a good reason not to, we should standardize components across the website.

**Comment by schalkneethling** [comment]
> Technical constraint for having two components doing the same thing?

Yes, there are technical reasons and at the time it was felt that the work it would take to overcome the challenge was not worth it.

In order to not hold up the work here, I am thinking we should:

1. Not have a lang selector in the footer for right no
2. Open an issue to talk through our options here and make a decision
3. Either leave the footer as is or, add the lang selector to all footers so we are consistent across the site.

Thoughts @malqinneh @atopal?

**Comment by atopal** [comment]
We currently don't have a language selector in the footer. I think, given the technical limitations we have, it's fine to leave it out in the redesigned footer.

**Comment by atopal** [comment]
Looks like this is done.
