### ISSUE TITLE
U - Invite users that become monthly subscribers to exclusive events and parties and offer discounts on swag

### ISSUE THREAD

**Issue by malqinneh** [mdn/kuma#6835]
# User story
As an MDN monthly subscriber, I want exclusive invites to parties and events, so I can feel good about my subscription

# Mock-ups

- [x] FAQ page (non subscriber)

![Sub Learn More - 01 - Incentive@1x](https://user-images.githubusercontent.com/4819906/78715314-3cbeb400-78eb-11ea-8e67-7ee7a827a756.jpg)

- [x] FAQ page (subscriber access only)
 
![Sub_Thank-You - 02 - Incentive@2x](https://user-images.githubusercontent.com/4819906/78720755-3ed94080-78f4-11ea-849d-e603d65b99e1.jpg)

- [x] Thank you page (subscriber access only)

![Sub Thank You - 01 - Incentive@1x](https://user-images.githubusercontent.com/4819906/78720737-37199c00-78f4-11ea-9f1f-4858fd0b3d3e.jpg)

- [x] User setting (before subscription)

![MDN_Profile - 01 - Incentive](https://user-images.githubusercontent.com/4819906/78720389-9b882b80-78f3-11ea-88cb-9f5b76e421dd.jpg)

- [x] User setting (after subscription)

![MDN_Profile - 03 - Incentive](https://user-images.githubusercontent.com/4819906/78720390-9f1bb280-78f3-11ea-92cb-34ab3e480850.jpg)

# Acceptance criteria

- [x] Identified opportunities where MDN can invite paying subscribers (All Hands, Mozilla Sponsored Conferences, etc)
- [x] Legal approval on copy once its in the FAQ/account prompt
- [x] Engineering sign off on mock-ups/solutions
- [x] Copy and front-end updated on production user account settings
- [x] Copy and front-end updated on production subscription landing page
- [x] Copy and front-end updated on production subscription thank you page

# Tasks

1. - [x] Planning doc with opportunities for inviting subscribers
2. - [x] Ask stakeholders to contribute to planning doc
3. - [x] Add copy to FAQ and account settings page(s)
4. - [x] Mock-ups, copy, assets are ready for engineering
