### ISSUE TITLE
A - Assumption Test: Automated translation is effective enough to be useful to us

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6838]
# Context

# Acceptance Criteria
- [x] [research project page completed](https://docs.google.com/document/d/1dR0qzoeSwMT0gpxc6tgLqbZT-u-v_1LMVLv9zVpPK1U/edit#)
- [x] method agreed on
- [ ] results documented and shared
- [ ] decision made and documented

# Possible ways to test this
- [ ] Take a few articles and copy/paste them into Google Translate for some languages. Score with native speaker. Check how it handles code
- [ ] Add happiness survey to pages and compare automatically translated content
- [ ] get baseline satisfaction manually translated french article, replace by automated translation check satisfaction change
- [ ] Check all of this separately for reference vs tutorial
- [ ] run survey where you ask native speakers to score automatically translated article.

# Tasks/process

1. Choose 3 guides/tutorials, and 5 reference pages to run the experiment on. Make sure they have a healthy variety of content types contained in them, for example prose, lists, code blocks, tables...  
2. Choose 5 languages to run the experiment on — they should be languages that we have a significant population reading on MDN, and that we can find people to help us with! Chinese, Brazilian Portugese, French, Spanish, Russian?
3. For each language, try to find at least 2 people who can help.
4. Translate the chosen articles into the chosen languages.
5. Write a set of criteria to mark the traslations against.
6. Get the helpers to mark the articles, and provide additional commentary.
7. collate feedback.

**Comment by chrisdavidmills** [comment]
@atopal process for doing this experiment written above; what do you think?
