### ISSUE TITLE
A - Assumption Test:  If we don't support L10n, we'll see a massive drop in task completion

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#6839]
# Context
Task completion is one of our KPI metrics. The assumption is that L10n is critical for people's success on the site. 

# Acceptance Criteria
- [x] [research project page completed](https://docs.google.com/document/d/1dR0qzoeSwMT0gpxc6tgLqbZT-u-v_1LMVLv9zVpPK1U/edit#)
- [x] method agreed on
- [x] results documented and shared
- [x] decision made and documented

# Tasks
- [ ] Research project template ready
- [ ] Task completion measured for all locales
- [ ] Task completion measured for French
- [ ] Task completion measured for Chinese
- [ ] Task completion measured for Russian
- [ ] Task completion measured for Spanish
- [ ] Task completion measured for German
- [ ] Results documented
- [ ] Results shared

# Possible ways to test this
- [ ] Remove properly localized articles and check whether that has affect on task completion
- [ ] Add properly localized articles and check whether that has affect on task completion
