### ISSUE TITLE
E - Assess getting lighthouse performance score to 95 (mobile)

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#6893]
# Epic 
Assess getting lighthouse performance score to 95 (mobile)

# Acceptance criteria
- [x] [Time-boxed investigation of performance on mobile maybe 1 week each front-end/back-end](https://github.com/mdn/kuma/issues/6894)
- [x] [Report based on investigation](https://github.com/mdn/kuma/issues/6895)
- [x] Low hanging fruits identified and possibly selected for upcoming sprints

**Comment by tobinmori** [comment]
Report is here: 

https://github.com/mdn/kuma/issues/6934#issuecomment-622497603
