### ISSUE TITLE
U - Define estimated effort of refactoring to improve mobile performance

### ISSUE THREAD

**Issue by tobinmori** [mdn/kuma#6895]
**Acceptance Criteria**

- [x] Using report generated in #6894, provide estimated level of effort for each refactor. 
- [x] Make a call on whether we have any low hanging fruits that we want to implement soon.
- [ ] Identify whether there is suboptimal use of Sass mixins

**Comment by atopal** [comment]
We met to discuss the assessment and concluded that there were no low hanging fruit, only things that would be beneficial, but quite large in scope.

**Comment by bensternthal** [comment]
Re-closing based on previous comment.
