### ISSUE TITLE
T - UX/UI for Account Settings (Desktop)

### ISSUE THREAD

**Issue by malqinneh** [mdn/kuma#7013]
# Task 
UX/UI for Account Settings (Desktop)

# Acceptance Criteria
- [x] All current account options are included in new design
- [x] Engineering sign-off
- [x] Product manager sign-off
