### ISSUE TITLE
T - Migrate kuma app to AWS EKS Cluster

### ISSUE THREAD

**Issue by limed** [mdn/kuma#7034]
**Summary**
Migrate kuma and kumascript from the current cluster to the AWS managed EKS kubernetes cluster

**Rationale**
Kuma is currently running on a old version of kubernetes that is considered EOL'ed and the IT-SE (Service Engineering) team would like to take the opportunity to migrate the app from its current cluster which was built using kops to the AWS managed kubernetes service (EKS) for better support and ease of underlying hardware upgrades going forward.

**Work involved**
I anticipate that work for this might take up to a week and the I have scoped out some of the tasks that need to be done before we can migrate

- [x] Stand up new EKS Clusters on `us-west-2` and `eu-central-1` (Completed in mdn/infra#394 & mdn/infra#396)
- [x] Modify AWS resources to accept new EKS Clusters (Completed in: mdn/infra#397)
- [x] Update kubernetes apiVersion for deployment manifest (PR: mdn/infra#399)
- [x] Update Jenkins job to be able to push code to the new clusters (Issue: #7049)
- [x] Stand up and test MDN on the 2 new EKS clusters (`us-west-2` and `eu-central-1`)
- [x] Switch traffic for stage to the new `us-west-2` EKS cluster
- [x] Switch traffic for standby to the new `eu-central-1` EKS cluster
- [x] Switch traffic for prod to the new `us-west-2` EKS cluster

**Notes**
I have already stood up MDN on a cluster in `eu-central-1` but have not switched DNS yet and also updated jenkins to start pushing to that cluster yet just need to do some testing to make sure that everything looks alright on that end

**Comment by escattone** [comment]
@limed and I did the following today:
- Copied all of the legacy files on EFS (`/mdn/www/{diagrams,presentations,samples}/*`) to both the `mdn-media-stage` and `mdn-media-prod` S3 buckets.
- Added three new behaviors (for `diagrams/*`, `presentations/*`, and `samples/*`) to both the primary stage and primary production CloudFront CDN's which route that traffic (if there's any) away from our Django instances and to the S3 buckets above.

The consequences of the above are:
- We can remove the code within Kuma related to serving the legacy files. I'll submit a PR for that next week.
- We are very close to being able to remove EFS altogether. We still use EFS for `humans.txt`, `lastsync.txt`, and the sitemap files, but I'm going to look into changing that, and then our use of EFS will finally die.

**Comment by escattone** [comment]
After we switch-over to the new AWS EKS cluster in Oregon for MDN stage and production (scheduled for tomorrow morning at 10am Pacific time), here are all of the good things that will have come out of the work on this task during sprint `Hotel`:
- [ ] The management and maintenance of all of our Kubernetes clusters will have been reduced/simplified by using AWS' EKS clusters for both the main cluster in Oregon and the standby cluster in Germany, instead of our current `kops`-generated custom clusters.
- [ ] We scaled-down the `web` and `ssr` deployments by 50%, which in turn enabled the next result.
- [ ] We reduced the number of nodes in our Oregon cluster (which contains both the stage and production instances of MDN) by 33% (from 15 nodes to 10 nodes). This means 5 less `m5.xlarge` EC2 instances which translates to a cost savings somewhere between $500-$1K per month.
- [ ] @limed added horizontal-pod-autoscalers (HPA's) to both the stage and production instances of MDN. This means that when traffic to MDN increases to a point that the current number of pods in the deployments can't handle, those deployments are automatically scaled-up to handle the increased traffic, and then later scaled-down when the traffic decreases.
- [ ] We are no longer dependent on EFS, since we now store the legacy files (the ancient `diagrams`, `presentations`, and `samples` files) and the sitemap files on S3 (see https://github.com/mdn/kuma/pull/7170). All of our file attachments, sitemap files, and legacy files are now served by S3 via the primary CDN (on both stage and production). There are no longer any files stored-on or served-from EFS. 🎉 
- [ ] A large chunk, perhaps around 30%, of our MDN Kubernetes code is related to EFS and will be removed (by a PR that I'm working on), greatly simplifying that code base and also will, we suspect, eliminate the "stuck node" problem that we often see (which often complicates our production/stage pushes).

**Comment by escattone** [comment]
Just finished creating https://github.com/mdn/infra/pull/418

**Comment by escattone** [comment]
FYI, I also made sure that we enable cross-zone load balancing when we create our ELB via Kubernetes, since our EKS clusters as well as our current KOPS-generated cluster are multi-AZ
(see https://github.com/mdn/infra/pull/417).

**Comment by escattone** [comment]
FYI, forgot to mention earlier that https://github.com/mdn/kuma/pull/7142, which removes the code within Kuma that serves legacy files, has been merged and released to stage and production.

**Comment by escattone** [comment]
https://github.com/mdn/infra/pull/429
https://github.com/mdn/infra/pull/430

**Comment by escattone** [comment]
This is done.
