### ISSUE TITLE
Grizzly: Jinja custom banner template tag

### ISSUE THREAD

**Issue by schalkneethling** [mdn/kuma#7134]
# User story

As a developer, I want to be able to show the banners that were added via the Django admin on the front end using a Jinja template tag.

# Acceptance criteria

- [ ] Can successfully show banners added via Django admin on the front end using the template tag.
- [ ] Correct theme is applied to banner
- [ ] Disabling and enabling banners works as expected on the front end

# Tasks

1. - [ ] Create HTML banner template
2. - [ ] Ensure existing styling and JS applies correctly to the above template
3. - [ ] Create a custom template tag

Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1539488
