### ISSUE TITLE
E - Launch Subscriptions

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#7151]
# Epic 
Launch Subscriptions

# Acceptance criteria
- [ ] FAQ is complete
- [ ] comms plan is agreed on
- [ ] full dashboard set up and shared with stakeholders
- [ ] Subscriptions launched to subset of users
- [ ] Subscriptions launched to all users
