### ISSUE TITLE
O - Make it easy to sign up

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#7153]
# Objective
Make it easy to sign up

*Ideally, this is in the issue title, but if not, you can put it here. If so, delete this section.*

# Acceptance Criteria
- [x] **KR:** Free membership accounts rolled out
    - [x] Streamlined user first-experience shipped
    - [x] Automated account managment
    - [x] Google Auth integration shipped
    - [x] User flow instrumented
