### ISSUE TITLE
E - Marketing email capability in place 

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#7156]
# Epic | Milestone 
We want a Marketing email capability in place so that we can alert users of our new subscription service 

# Acceptance criteria
- [ ] We can send people marketing emails 
- [ ] People can subscribe during account creation and later
- [ ] People can unsubscribe 
- [ ] An Admin can unsubscribe users 
- [x] Our method has been approved by Legal 
- [ ] There is a capability to send emails to a sub-set of users (who are paying subscribers)
