### ISSUE TITLE
E - Get admin services ready for launch

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#7157]
# User story
As the MDN PM I want assurance that all supporting services for subscriptions are in place so we don't have unexpected surprises

# Acceptance criteria

- [x] Legal has signed off on flow and implementation
- [x] support has mailing list in place
- [x] support has made decision on supporting launch or not
- [x] Stripe contract signed or legal has accepted current contract
- [ ] Email service contract has been signed.
- [ ] Accounting has signed off on revenue plan

**Comment by atopal** [comment]
Abandoned in favor of https://github.com/mdn/kuma/issues/7317
