### ISSUE TITLE
T - Acct Settings: UX/UI support

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#7159]
# Task 
T - Acct Settings: UX/UI support 

# Checklist 
- [x] Refactor settings page with [Team feedback ](https://docs.google.com/document/d/13kILBvON9XuxUoFEssfzzb24PYVYKfZFX_2Zw4Nqq8A/edit?usp=sharing)
- [x] Share [revised settings page](https://share.goabstract.com/1921e4af-b81c-494b-a199-b51ba9c7b4f6?mode=design&sha=b097ab8182e296f936d7e3fb283582307b25ad17) with Team
- [x] Engineering and product sign-off

**Comment by malqinneh** [comment]
Updates have been completed for this sprint. Closing.
