### ISSUE TITLE
E - Prepare to Reduce payment friction with monthly subscription

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#7187]
# Epic 
E - Prepare to Reduce payment friction with monthly subscription

# Acceptance criteria
- [x] Solutions with the team have been generated
- [x] Solutions with the admin team have been shortlisted
- [x] Red flags from stakeholders have been resolved
- [x] Shortlisted solutions have been explored
- [ ] OKRs for Q3 based on selected solutions have been updated

# Action Items
- [x] Generated solutions with the team
- [ ] Evaluated all solutions with the admin team
- [ ] Presented shortlisted solutions to stakeholders
- [ ] Explored product constraints for solution 1, 2, 3, etc...

**Comment by malqinneh** [comment]
We're still pending input from the finance team on accepting additional currencies - we may not hear back by the end of Sprint this week. Looking to @atopal to decide whether we're good to close this issue for now given that we're removing subscriptions OKRs from Q3.

**Comment by atopal** [comment]
Yes, let's do that. Thanks Mustafa!
