### ISSUE TITLE
E - Complete technical work for subscriptions

### ISSUE THREAD

**Issue by chinikes** [mdn/kuma#7292]
The goal here is to finish up all of the work on the platform to the point where all we have to do is flip a switch once we have the green light.

# Acceptance Criteria 
- [ ] Account Settings is rebuilt with react
- [ ] Account Settings follows new streamlined design
- [ ] Email delivery is hooked up to production sendinblue account
