### ISSUE TITLE
E - Create documentation of all components and styles on MDN (desktop and mobile)

### ISSUE THREAD

**Issue by malqinneh** [mdn/kuma#7297]
### Epic
E - Create documentation of all components and styles on MDN

### Acceptance criteria
- [ ] Components and styles are designed and shared with the team in Abstract
- [ ] Components and styles are documented in Storybook and shared with the team
- [ ] Components and styles issues, redundancies, and improvements have been resolved with the team
- [ ] 

### Acceptance criteria
- [ ] Create [header] components and styles (desktop)
- [ ] Create [header] components and styles (mobile)
- [ ] Create [footer] components and styles (desktop)
- [ ] Create [footer] components and styles (mobile)
- [ ] Create [sidebar] components and styles (desktop)
- [ ] Create [sidebar] components and styles (mobile)
- [ ] Create [table of contents] components and styles (desktop)
- [ ] Create [table of contents] components and styles (mobile)
- [ ] Create [account settings] components and styles (desktop)
- [ ] Create [account settings] components and styles (mobile)
- [ ] Align [web technologies] page with consistent components and styles (desktop)
- [ ] Align [web technologies] page with consistent components and styles (mobile)
- [ ] Align [learn web] development] page with consistent components and styles (desktop)
- [ ] Align [learn web development] page with consistent components and styles (mobile)
- [ ] Align [about us] page with consistent components and styles (desktop)
- [ ] Align [about us] page with consistent components and styles (mobile)
- [ ] Align [feedback] page with consistent components and styles (desktop)
- [ ] Align [feedback] page with consistent components and styles (mobile)
- [ ] Align [feedback] page with consistent components and styles (desktop)
- [ ] Align [platform feature] page with consistent components and styles (desktop)
- [ ] Align [platform feature] page with consistent components and styles (mobile)
- [ ] Align [search results] page with consistent components and styles (desktop)
- [ ] Align [search results] page with consistent components and styles (mobile)

**Comment by schalkneethling** [comment]
I would say these two would be a good fit for a sprint:

- Create [header] components and styles (desktop)
- Create [header] components and styles (mobile)

I would link them to:

- https://github.com/mdn/mdn-fiori/issues/170
- https://github.com/mdn/mdn-fiori/issues/171
- https://github.com/mdn/mdn-fiori/issues/172
