### ISSUE TITLE
E - L10n decicion made and communicated

### ISSUE THREAD

**Issue by atopal** [mdn/kuma#7320]
Acceptance Criteria
- [ ] Proposal made and documented
- [ ] Proposal communicated Mozilla internally
- [ ] Decision communicated externally
